# Intermediate Preprocessing

In [26]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
%matplotlib inline 

In [27]:
listings = pd.read_csv('data\listings.csv')
listings.head()

url  \
0  https://www.renthop.com/listings/gold-st/12c/1...   
1  https://www.renthop.com/listings/gold-st/9d/15...   
2  https://www.renthop.com/listings/141-east-56th...   
3  https://www.renthop.com/listings/west-street/2...   
4  https://www.renthop.com/listings/382-wadsworth...   

                         address  \
0                       Gold St.   
1                       Gold St.   
2  141 East 56th Street, Apt 11A   
3                   west street    
4      382 Wadsworth Ave, Apt 4B   

                                        neighborhood    rent   beds   baths  \
0  Downtown Brooklyn, Northwestern Brooklyn, Broo...  $3,395  1_Bed  1_Bath   
1  Downtown Brooklyn, Northwestern Brooklyn, Broo...  $3,071  1_Bed  1_Bath   
2         Midtown East, Midtown Manhattan, Manhattan  $4,925  2_Bed  1_Bath   
3  Financial District, Downtown Manhattan, Manhattan  $3,750  1_Bed  1_Bath   
4  Fort George, Washington Heights, Upper Manhatt...  $4,195  5_Bed  2_Bath   

       flexs  
0        NaN  
1        NaN  
2        NaN  
3  /_Flex_3_  
4        NaN

In [28]:
listings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 7 columns):
url             2000 non-null object
address         1999 non-null object
neighborhood    2000 non-null object
rent            2000 non-null object
beds            2000 non-null object
baths           2000 non-null object
flexs           267 non-null object
dtypes: object(7)
memory usage: 109.5+ KB


In [29]:
listings.describe()

url      address  \
count                                                2000         1999   
unique                                               1848         1418   
top     https://www.renthop.com/listings/28th-st/50/15...  Wall Street   
freq                                                    3           19   

                                        neighborhood    rent   beds   baths  \
count                                           2000    2000   2000    2000   
unique                                           129     684     12      11   
top     Hell's Kitchen, Midtown Manhattan, Manhattan  $2,800  1_Bed  1_Bath   
freq                                             173      34    694    1539   

            flexs  
count         267  
unique          8  
top     /_Flex_2_  
freq          112

- Fixing Beds Feature

In [30]:
listings['beds'].unique()

array(['1_Bed', '2_Bed', '5_Bed', 'Studio', '_2_Bed', '3_Bed', '4_Bed',
       'Loft', 'Room', '_5_Bed', '_Room', '_4_Bed'], dtype=object)

We can few duplicate categories. i.e. '5_Bed' and '\_5_Bed' are same

In [31]:
# Setup  for removing extra '_' from categories

dumy_strs = pd.Series(["_x_Bed","x_Bed"])
dumy_strs.map(lambda x: x[1:] if x.startswith('_') else x)

0    x_Bed
1    x_Bed
dtype: object

In [32]:
# Removindg stating '_'
listings['beds'] = listings['beds'].map(lambda x: x[1:] if x.startswith('_') else x) 

In [33]:
listings['beds'].unique()

array(['1_Bed', '2_Bed', '5_Bed', 'Studio', '3_Bed', '4_Bed', 'Loft',
       'Room'], dtype=object)

In [34]:
# Futher Fixing - Setting other Categoris to 0-Beds

listings['beds'] = listings['beds'].map(lambda x: x.replace('_Bed', '')) 
listings['beds'] = listings['beds'].map(lambda x: x.replace('Studio', '0')) 
listings['beds'] = listings['beds'].map(lambda x: x.replace('Loft', '0'))
listings['beds'] = listings['beds'].map(lambda x: x.replace('Room', '0'))

In [35]:
# Contering to Numeric

listings['beds'] = pd.to_numeric(listings['beds'])
listings['beds'].unique()

array([1, 2, 5, 0, 3, 4], dtype=int64)

- Fixing baths feature

In [36]:
listings['baths'].unique()

array(['1_Bath', '2_Bath', '3_Bath', '1.5_Bath', '2.5_Bath', '4_Bath',
       '_2.5_Bath', '_1_Bath', '4.5_Bath', '_2_Bath', '5_Bath'],
      dtype=object)

In [37]:
listings['baths'] = listings['baths'].map(lambda x: x[1:] if x.startswith('_') else x) 
listings['baths'] = listings['baths'].map(lambda x: x.replace('_Bath', '')) 

In [38]:
# Contering to Numeric

listings['baths'] = pd.to_numeric(listings['baths'])
listings['baths'].unique()

array([1. , 2. , 3. , 1.5, 2.5, 4. , 4.5, 5. ])

- Fixing Flexes 

In [39]:
listings['flexs'].unique()

array([nan, '/_Flex_3_', '/_Flex_2_', '/_Flex_1_', '/_Flex_4_',
       '/_Flex_5_', '/_Flex_6_', '_/_Flex_3_', '/_Flex_2__'], dtype=object)

In [40]:
# listings[listings['flexs'].notnull()]['flexs']

In [41]:
listings['flexs'] = listings[listings['flexs'].notnull()]['flexs'].map(lambda x: x[1:] if x.startswith('_') else x)
listings['flexs'] = listings[listings['flexs'].notnull()]['flexs'].map(lambda x: x[1:] if x.endswith('_') else x)

In [42]:
listings['flexs'].unique()

array([nan, '_Flex_3_', '_Flex_2_', '_Flex_1_', '_Flex_4_', '_Flex_5_',
       '_Flex_6_', '_Flex_2__'], dtype=object)

In [47]:
listings['flexs'] = listings[listings['flexs'].notnull()]['flexs'].map(lambda x: x.replace('_Flex_', '')) 
listings['flexs'] = listings[listings['flexs'].notnull()]['flexs'].map(lambda x: x.replace('_', '')) 

In [48]:
listings['flexs'].unique()

array([nan, '3', '2', '1', '4', '5', '6'], dtype=object)

In [50]:
# Contering to Numeric

listings['flexs'] = pd.to_numeric(listings['flexs'])
listings['flexs'].unique()

array([nan,  3.,  2.,  1.,  4.,  5.,  6.])

- Fixing Rent

In [53]:
listings['rent'] = listings['rent'].map(lambda x: str(x).replace('$','').replace(',','')).astype('int') 

In [55]:
listings.head(3)

url  \
0  https://www.renthop.com/listings/gold-st/12c/1...   
1  https://www.renthop.com/listings/gold-st/9d/15...   
2  https://www.renthop.com/listings/141-east-56th...   

                         address  \
0                       Gold St.   
1                       Gold St.   
2  141 East 56th Street, Apt 11A   

                                        neighborhood  rent  beds  baths  flexs  
0  Downtown Brooklyn, Northwestern Brooklyn, Broo...  3395     1    1.0    NaN  
1  Downtown Brooklyn, Northwestern Brooklyn, Broo...  3071     1    1.0    NaN  
2         Midtown East, Midtown Manhattan, Manhattan  4925     2    1.0    NaN

In [56]:
listings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 7 columns):
url             2000 non-null object
address         1999 non-null object
neighborhood    2000 non-null object
rent            2000 non-null int32
beds            2000 non-null int64
baths           2000 non-null float64
flexs           267 non-null float64
dtypes: float64(2), int32(1), int64(1), object(3)
memory usage: 101.7+ KB


### Saving data

In [58]:
listings.to_csv('data\listings_interm.csv', index = False)