# Intermediate Preprocessing

In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
%matplotlib inline 

In [2]:
listings = pd.read_csv('data\listings.csv')
listings.head()

url  \
0  https://www.renthop.com/listings/gold-st/12c/1...   
1  https://www.renthop.com/listings/gold-st/9d/15...   
2  https://www.renthop.com/listings/141-east-56th...   
3  https://www.renthop.com/listings/west-street/2...   
4  https://www.renthop.com/listings/382-wadsworth...   

                         address  \
0                       Gold St.   
1                       Gold St.   
2  141 East 56th Street, Apt 11A   
3                   west street    
4      382 Wadsworth Ave, Apt 4B   

                                        neighborhood    rent   beds   baths  \
0  Downtown Brooklyn, Northwestern Brooklyn, Broo...  $3,395  1_Bed  1_Bath   
1  Downtown Brooklyn, Northwestern Brooklyn, Broo...  $3,071  1_Bed  1_Bath   
2         Midtown East, Midtown Manhattan, Manhattan  $4,925  2_Bed  1_Bath   
3  Financial District, Downtown Manhattan, Manhattan  $3,750  1_Bed  1_Bath   
4  Fort George, Washington Heights, Upper Manhatt...  $4,195  5_Bed  2_Bath   

       flexs  
0        NaN  
1        NaN  
2        NaN  
3  /_Flex_3_  
4        NaN

In [3]:
listings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 7 columns):
url             2000 non-null object
address         1999 non-null object
neighborhood    2000 non-null object
rent            2000 non-null object
beds            2000 non-null object
baths           2000 non-null object
flexs           267 non-null object
dtypes: object(7)
memory usage: 109.5+ KB


In [4]:
listings.describe()

url      address  \
count                                                2000         1999   
unique                                               1848         1418   
top     https://www.renthop.com/listings/28th-st/50/15...  Wall Street   
freq                                                    3           19   

                                        neighborhood    rent   beds   baths  \
count                                           2000    2000   2000    2000   
unique                                           129     684     12      11   
top     Hell's Kitchen, Midtown Manhattan, Manhattan  $2,800  1_Bed  1_Bath   
freq                                             173      34    694    1539   

            flexs  
count         267  
unique          8  
top     /_Flex_2_  
freq          112

### Fixing Beds Feature

In [5]:
listings['beds'].unique()

array(['1_Bed', '2_Bed', '5_Bed', 'Studio', '_2_Bed', '3_Bed', '4_Bed',
       'Loft', 'Room', '_5_Bed', '_Room', '_4_Bed'], dtype=object)

We can few duplicate categories. i.e. '5_Bed' and '\_5_Bed' are same

In [6]:
# Setup  for removing extra '_' from categories

dumy_strs = pd.Series(["_x_Bed","x_Bed"])
dumy_strs.map(lambda x: x[1:] if x.startswith('_') else x)

0    x_Bed
1    x_Bed
dtype: object

In [7]:
# Removindg stating '_'
listings['beds'] = listings['beds'].map(lambda x: x[1:] if x.startswith('_') else x) 

In [8]:
listings['beds'].unique()

array(['1_Bed', '2_Bed', '5_Bed', 'Studio', '3_Bed', '4_Bed', 'Loft',
       'Room'], dtype=object)

In [9]:
# Futher Fixing - Setting other Categoris to 0-Beds

listings['beds'] = listings['beds'].map(lambda x: x.replace('_Bed', '')) 
listings['beds'] = listings['beds'].map(lambda x: x.replace('Studio', '0')) 
listings['beds'] = listings['beds'].map(lambda x: x.replace('Loft', '0'))
listings['beds'] = listings['beds'].map(lambda x: x.replace('Room', '0'))

In [10]:
# Contering to Numeric

listings['beds'] = pd.to_numeric(listings['beds'])
listings['beds'].unique()

array([1, 2, 5, 0, 3, 4], dtype=int64)

### Fixing baths feature

In [11]:
listings['baths'].unique()

array(['1_Bath', '2_Bath', '3_Bath', '1.5_Bath', '2.5_Bath', '4_Bath',
       '_2.5_Bath', '_1_Bath', '4.5_Bath', '_2_Bath', '5_Bath'],
      dtype=object)

In [12]:
listings['baths'] = listings['baths'].map(lambda x: x[1:] if x.startswith('_') else x) 
listings['baths'] = listings['baths'].map(lambda x: x.replace('_Bath', '')) 

In [13]:
# Contering to Numeric

listings['baths'] = pd.to_numeric(listings['baths'])
listings['baths'].unique()

array([1. , 2. , 3. , 1.5, 2.5, 4. , 4.5, 5. ])

### Fixing Flexes 

In [14]:
listings['flexs'].unique()

array([nan, '/_Flex_3_', '/_Flex_2_', '/_Flex_1_', '/_Flex_4_',
       '/_Flex_5_', '/_Flex_6_', '_/_Flex_3_', '/_Flex_2__'], dtype=object)

In [15]:
# listings[listings['flexs'].notnull()]['flexs']

In [16]:
listings['flexs'] = listings[listings['flexs'].notnull()]['flexs'].map(lambda x: x[1:] if x.startswith('_') else x)
listings['flexs'] = listings[listings['flexs'].notnull()]['flexs'].map(lambda x: x[1:] if x.endswith('_') else x)

In [17]:
listings['flexs'].unique()

array([nan, '_Flex_3_', '_Flex_2_', '_Flex_1_', '_Flex_4_', '_Flex_5_',
       '_Flex_6_', '_Flex_2__'], dtype=object)

In [18]:
listings['flexs'] = listings[listings['flexs'].notnull()]['flexs'].map(lambda x: x.replace('_Flex_', '')) 
listings['flexs'] = listings[listings['flexs'].notnull()]['flexs'].map(lambda x: x.replace('_', '')) 

In [19]:
listings['flexs'].unique()

array([nan, '3', '2', '1', '4', '5', '6'], dtype=object)

In [20]:
# Contering to Numeric

listings['flexs'] = pd.to_numeric(listings['flexs'])
listings['flexs'].unique()

array([nan,  3.,  2.,  1.,  4.,  5.,  6.])

Nan here means we have no Flex

In [21]:
listings['flexs'] = listings['flexs'].fillna(0)


In [22]:
listings['flexs'].unique()

array([0., 3., 2., 1., 4., 5., 6.])

In [23]:
listings['flexs'].value_counts()

0.0    1733
2.0     113
3.0      86
4.0      35
1.0      29
5.0       3
6.0       1
Name: flexs, dtype: int64

### Fixing Rent

In [24]:
listings['rent'] = listings['rent'].map(lambda x: str(x).replace('$','').replace(',','')).astype('int') 

In [25]:
listings.head(3)

url  \
0  https://www.renthop.com/listings/gold-st/12c/1...   
1  https://www.renthop.com/listings/gold-st/9d/15...   
2  https://www.renthop.com/listings/141-east-56th...   

                         address  \
0                       Gold St.   
1                       Gold St.   
2  141 East 56th Street, Apt 11A   

                                        neighborhood  rent  beds  baths  flexs  
0  Downtown Brooklyn, Northwestern Brooklyn, Broo...  3395     1    1.0    0.0  
1  Downtown Brooklyn, Northwestern Brooklyn, Broo...  3071     1    1.0    0.0  
2         Midtown East, Midtown Manhattan, Manhattan  4925     2    1.0    0.0

In [26]:
listings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 7 columns):
url             2000 non-null object
address         1999 non-null object
neighborhood    2000 non-null object
rent            2000 non-null int32
beds            2000 non-null int64
baths           2000 non-null float64
flexs           2000 non-null float64
dtypes: float64(2), int32(1), int64(1), object(3)
memory usage: 101.7+ KB


### Zip Codes
Using Google Maps For getting Related Zip Codes 

In [27]:
# !pip install -U googlemaps

In [28]:
listings.loc[3,['address']].values[0] + ' ' + listings.loc[3,['neighborhood']].values[0].split(', ')[-1]

'west street  Manhattan'

In [29]:

def get_key():
    file_path = "Secrets\key.txt"
    with open(file_path, 'r') as file: 
          return file.read()


In [30]:
import googlemaps 
 
gmaps = googlemaps.Client(key=get_key()) 
 
# removing ',' from a record | So, we can get the cleaned string to get zipcode
r = listings.loc[1,['address']].values[0] + ' ' + listings.loc[1,['neighborhood']].values[0].split(', ')[-1] 
r 

'Gold St. Brooklyn'

In [31]:
# Fetching Related data
geocode_result = gmaps.geocode(r) 
 
geocode_result 

[{'address_components': [{'long_name': 'Gold Street',
    'short_name': 'Gold St',
    'types': ['route']},
   {'long_name': 'Downtown Brooklyn',
    'short_name': 'Downtown Brooklyn',
    'types': ['neighborhood', 'political']},
   {'long_name': 'Brooklyn',
    'short_name': 'Brooklyn',
    'types': ['political', 'sublocality', 'sublocality_level_1']},
   {'long_name': 'Kings County',
    'short_name': 'Kings County',
    'types': ['administrative_area_level_2', 'political']},
   {'long_name': 'New York',
    'short_name': 'NY',
    'types': ['administrative_area_level_1', 'political']},
   {'long_name': 'United States',
    'short_name': 'US',
    'types': ['country', 'political']},
   {'long_name': '11201', 'short_name': '11201', 'types': ['postal_code']}],
  'formatted_address': 'Gold St, Brooklyn, NY 11201, USA',
  'geometry': {'bounds': {'northeast': {'lat': 40.706913, 'lng': -73.9807991},
    'southwest': {'lat': 40.6920537, 'lng': -73.9844722}},
   'location': {'lat': 40.699101

In [32]:
geocode_result[0]['address_components']

[{'long_name': 'Gold Street', 'short_name': 'Gold St', 'types': ['route']},
 {'long_name': 'Downtown Brooklyn',
  'short_name': 'Downtown Brooklyn',
  'types': ['neighborhood', 'political']},
 {'long_name': 'Brooklyn',
  'short_name': 'Brooklyn',
  'types': ['political', 'sublocality', 'sublocality_level_1']},
 {'long_name': 'Kings County',
  'short_name': 'Kings County',
  'types': ['administrative_area_level_2', 'political']},
 {'long_name': 'New York',
  'short_name': 'NY',
  'types': ['administrative_area_level_1', 'political']},
 {'long_name': 'United States',
  'short_name': 'US',
  'types': ['country', 'political']},
 {'long_name': '11201', 'short_name': '11201', 'types': ['postal_code']}]

Dictonary having 'types' key with ['postal_code'] 
have 'short_name' key with zipcode

In [33]:
# looping trough this data to get zipcode
for piece_dict in geocode_result[0]['address_components']: 
    if 'postal_code' in piece_dict['types'] : 
        print(piece_dict['short_name']) 

11201


**Putting all together**

In [34]:
import re 
from IPython.display import clear_output


def get_zip(row): 
    """
    Source: ML Blueprints
    """
    # Remove Previous Print and add new
    clear_output(wait=True)
    print("...")
    print("...")
    
    try: 
        # removing ','
        addr = row['address'] + ' ' + row['neighborhood'].split(', ')[-1]     
        
        print(addr)
    
        if re.match('^\d+\s\w', addr): 
            geocode_result = gmaps.geocode(addr) 
            for piece in geocode_result[0]['address_components']: 
                if 'postal_code' in piece['types']: 
                    return piece['short_name'] 
                else: 
                    pass 
        else: 
            return np.nan 
    except: 
        return np.nan

In [35]:
listings['zip'] = listings.apply(get_zip, axis=1) 

...
...
2 Gold Street, Apt 1210 Manhattan


In [36]:
listings['zip'].unique()

array([nan, '10022', '10040', '10016', '10065', '11211', '10033', '10282',
       '10024', '10280', '10021', '10005', '10128', '10014', '11201',
       '10018', '10038', '10023', '11225', '10009', '10034', '10032',
       '10075', '11216', '10011', '10003', '10027', '10037', '11221',
       '10025', '10017', '10019', '11215', '10036', '10028', '11222',
       '10001', '11238', '11226', '11228', '10006', '10031', '10013',
       '10029', '10002', '10012', '11206', '11235', '11377', '10007',
       '11219', '11214', '10039', '11213', '11220', '11101', '10035',
       '11207', '11102', '11210', '10304', '11203', '11249', '11105',
       '11209', '11237', '11218', '11233', '11230', '10463', '11385',
       '10306', '10010', '11375', '11205', '10026', '10030', None,
       '11217', '10471', '10468', '10552', '11236', '10162', '11231',
       '10004', '11435', '11208', '11229', '10453', '10069', '10701',
       '10456', '11379'], dtype=object)

Verify that None and np.nan are getting treated as NULLs

In [37]:
listings['zip'].value_counts()

10031    39
10036    33
10016    32
10019    31
10038    26
         ..
11236     1
10453     1
11208     1
10456     1
10468     1
Name: zip, Length: 92, dtype: int64

In [38]:
dict(listings['zip'].value_counts()).keys()

dict_keys(['10031', '10036', '10016', '10019', '10038', '11216', '11221', '10009', '10023', '10032', '10024', '10128', '11206', '10014', '10022', '10005', '11213', '11211', '10002', '10001', '10003', '10028', '10011', '11225', '10017', '10025', '10075', '11230', '11226', '10013', '10018', '10021', '10029', '11102', '11238', '11201', '10010', '10034', '11203', '10037', '10012', '10282', '11233', '10035', '11222', '11237', '10040', '11205', '10065', '11217', '11220', '11209', '11210', '11207', '11215', '10033', '10280', '10026', '10007', '11385', '11249', '11235', '11101', '11219', '10039', '10030', '10304', '10069', '11228', '11218', '10004', '10006', '10552', '10162', '10471', '11229', '10027', '10701', '11375', '10463', '10306', '11105', '11435', '11231', '11214', '11377', '11379', '11236', '10453', '11208', '10456', '10468'])

In [39]:
total_null = len(listings[listings['zip'].isnull()]['zip'])
total_null

1165

In [40]:
listings.shape[0] - total_null # we only got zip for this number of listings

835

We Lost most of the data, anyways that would be useful to have zip codes

### Saving data

In [41]:
listings.to_csv('data\listings_interm_with_null_zips.csv', index = False)

In [42]:
listings[listings['zip'].notnull()].to_csv('data\listings_interm_with_zips.csv', index = False)